spring:
  datasource:
    url: jdbc:h2:mem:test
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default-schema: CHALLENGE
        dialect: org.hibernate.dialect.H2Dialect

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

